### ISSUE TITLE
Rename to WireFox

### ISSUE THREAD

**Issue by Thann** [NilsIrl/MozWire#11] opened 2020-08-17 22:20 UTC
It's a travesty it wasn't done in the first place.

**Comment by NilsIrl** [comment] 2020-08-17 22:38
I'd love to, unfortunately, it's a bit late now :(

**Comment by Thann** [comment] 2020-08-17 23:10
I don't think so ¯\_(ツ)_/¯

**Comment by ilar** [comment] 2020-08-17 23:34
To be frank, it's kind of inconceivable that you think this is 'too late.'

Your branding is one of the most important parts of a project like this, because a good security product that isn't used- because nobody has heard of it, talks about it, or remembers it.... well, it may as well not even exist. Mozilla products already struggle against larger, more entrenched options that have more capital to throw about for capturing attention, why make things arbitrarily harder for a.... well, to be brutally honest, a really crappy name.

It would be like calling Firefox 'MozExplorer' or Thunderbird 'MozLook'.

**Comment by JohnCMoon** [comment] 2020-08-18 03:10
This app and the Mozilla VPN product aren't related to Firefox... I think MozWire is a better name myself!

**Comment by NilsIrl** [comment] 2020-08-18 12:14
Closing this:

MozWire appears in the first results of Google when you search for "MozWire" and "MozillaVPN for {Linux,macOS}". I don't know enough about SEO to know if this would be reproduced if the name was changed to "WireFox" and I don't want to take the risk.

**Closed as completed by NilsIrl** 2020-08-18 12:14 UTC

**Comment by guptadd** [comment] 2020-08-18 18:58
> MozWire appears in the first results of Google when you search for "MozWire" 

Yeah, and Bob's my uncle.
